// <auto-generated />
using GreenThumb_Henrik.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenThumb_Henrik.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231210041959_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GardenPlant", b =>
                {
                    b.Property<int>("GardensId")
                        .HasColumnType("int");

                    b.Property<int>("PlantsId")
                        .HasColumnType("int");

                    b.HasKey("GardensId", "PlantsId");

                    b.HasIndex("PlantsId");

                    b.ToTable("GardenPlant");
                });

            modelBuilder.Entity("GreenThumb_Henrik.Models.Garden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("GreenThumb_Henrik.Models.Instruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Instruction");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Give water",
                            PlantId = 3
                        },
                        new
                        {
                            Id = 2,
                            Name = "Give sunlight",
                            PlantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Repot plant when its gotten bigger",
                            PlantId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Distribute pesticide",
                            PlantId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Monitor temperature and humidity",
                            PlantId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Provide support so plant stays upright",
                            PlantId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Repot plant when its gotten bigger",
                            PlantId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Repot plant when its gotten bigger",
                            PlantId = 12
                        },
                        new
                        {
                            Id = 9,
                            Name = "Distribute pesticide",
                            PlantId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Distribute pesticide",
                            PlantId = 5
                        },
                        new
                        {
                            Id = 11,
                            Name = "Provide support so plant stays upright",
                            PlantId = 4
                        },
                        new
                        {
                            Id = 12,
                            Name = "Give water",
                            PlantId = 5
                        },
                        new
                        {
                            Id = 13,
                            Name = "Give sunlight",
                            PlantId = 5
                        },
                        new
                        {
                            Id = 14,
                            Name = "Monitor temperature and humidity",
                            PlantId = 5
                        },
                        new
                        {
                            Id = 15,
                            Name = "Give sunlight",
                            PlantId = 6
                        },
                        new
                        {
                            Id = 16,
                            Name = "Monitor Temperature and humidity",
                            PlantId = 7
                        },
                        new
                        {
                            Id = 17,
                            Name = "Give water",
                            PlantId = 8
                        },
                        new
                        {
                            Id = 18,
                            Name = "Distribute pesticide",
                            PlantId = 8
                        },
                        new
                        {
                            Id = 19,
                            Name = "Give water",
                            PlantId = 9
                        },
                        new
                        {
                            Id = 20,
                            Name = "Monitor temperature and humidity",
                            PlantId = 9
                        },
                        new
                        {
                            Id = 21,
                            Name = "Give sunlight",
                            PlantId = 10
                        },
                        new
                        {
                            Id = 22,
                            Name = "Distribute pesticide",
                            PlantId = 10
                        },
                        new
                        {
                            Id = 23,
                            Name = "Give water",
                            PlantId = 11
                        },
                        new
                        {
                            Id = 24,
                            Name = "Give sunlight",
                            PlantId = 12
                        },
                        new
                        {
                            Id = 25,
                            Name = "Distribute pesticide",
                            PlantId = 12
                        });
                });

            modelBuilder.Entity("GreenThumb_Henrik.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oak"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dandelion"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Venus Flytrap"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sunflower"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hemp"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Barrel Cactus"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bamboo"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Wheat"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Spider Plant"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Strawberry"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Jade Plant"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Banana"
                        });
                });

            modelBuilder.Entity("GreenThumb_Henrik.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GardenPlant", b =>
                {
                    b.HasOne("GreenThumb_Henrik.Models.Garden", null)
                        .WithMany()
                        .HasForeignKey("GardensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenThumb_Henrik.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenThumb_Henrik.Models.Garden", b =>
                {
                    b.HasOne("GreenThumb_Henrik.Models.User", "User")
                        .WithOne("Garden")
                        .HasForeignKey("GreenThumb_Henrik.Models.Garden", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenThumb_Henrik.Models.Instruction", b =>
                {
                    b.HasOne("GreenThumb_Henrik.Models.Plant", "Plant")
                        .WithMany("Instructions")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThumb_Henrik.Models.Plant", b =>
                {
                    b.Navigation("Instructions");
                });

            modelBuilder.Entity("GreenThumb_Henrik.Models.User", b =>
                {
                    b.Navigation("Garden")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
